import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script id="uuid-polyfill" strategy="beforeInteractive">
          {`(() => {
            if (typeof globalThis === "undefined") return;
            const g = globalThis;
            if (!g.crypto) g.crypto = {};
            if (typeof g.crypto.randomUUID === "function") return;
            g.crypto.randomUUID = function randomUUID() {
              const bytes = new Uint8Array(16);
              if (typeof g.crypto.getRandomValues === "function") {
                g.crypto.getRandomValues(bytes);
              } else {
                for (let i = 0; i < 16; i += 1) bytes[i] = Math.floor(Math.random() * 256);
              }
              bytes[6] = (bytes[6] & 0x0f) | 0x40;
              bytes[8] = (bytes[8] & 0x3f) | 0x80;
              const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
              return \`\${hex.slice(0, 8)}-\${hex.slice(8, 12)}-\${hex.slice(12, 16)}-\${hex.slice(16, 20)}-\${hex.slice(20)}\`;
            };
          })();`}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
